service: orders

frameworkVersion: "2"
# variablesResolutionMode: 20210219

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline-dotenv
  - serverless-offline

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk
    packager: "npm"
  serverless-offline:
    httpPort: 4000
    ignoreJWTSignature: true
  imageUploadBucket: imagebucket-dev


provider:
  name: aws
  region: eu-central-1
  # profile: swexception
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, 'dev'}

  apiGateway:
    restApiId: 95kq9eggu9
    restApiRootResourceId: zsd84g8moe

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    REGION: ${self:provider.region}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
          Resource: "*"

functions:
  getOrders:
    handler: "src/orders/getOrders.HANDLER"
    events:
      - http:
          path: /orders
          method: GET
          cors: true
  getOrder:
    handler: "src/orders/getOrderDetails.HANDLER"
    events:
      - http:
          path: /orders/{id}
          method: GET
          cors: true
  placeOrder:
    handler: "src/orders/placeOrder.HANDLER"
    events:
      - http:
          path: /orders/
          method: POST
          cors: true

resources:
  Resources:
    #dynamodb tables
    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: order
        AttributeDefinitions:
          - AttributeName: orderid
            AttributeType: "S"
          - AttributeName: userid
            AttributeType: "S"
          - AttributeName: timestamp
            AttributeType: "S"
          - AttributeName: status
            AttributeType: "S"
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: getStatus
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
          - IndexName: id-index
            KeySchema:
              - AttributeName: orderid
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
        BillingMode: PAY_PER_REQUEST
              
