openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: OpenAPI for orders management
  version: 0.1.0

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0/orders
- description: serverless offline
  url: http://localhost:4000/dev/orders

paths:
  /orders:
    $ref: "orders.yml"
  /orders/{id}:
    $ref: "ordersByID.yml"
  /checkout/:
    $ref: "checkout.yml"
  /checkout/{intent-id}/:
    $ref: "checkoutByID.yml"